;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Attribute.MovementSpeed",NewTagName="Attribute.MovementSpeedScale")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Player.BlackholeProjectile",DevComment="")
+GameplayTagList=(Tag="Ability.Player.MagicProjectile",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Player.TeleportProjectile",DevComment="")
+GameplayTagList=(Tag="Attribute.CurrentHealth",DevComment="Current Health")
+GameplayTagList=(Tag="Attribute.CurrentMana",DevComment="")
+GameplayTagList=(Tag="Attribute.MaxHealth",DevComment="Max Health")
+GameplayTagList=(Tag="Attribute.MaxMana",DevComment="")
+GameplayTagList=(Tag="Attribute.MovementSpeedScale",DevComment="")
+GameplayTagList=(Tag="GameplayEffect",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.BlackholeProjectile.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.BlackholeProjectile.Cost",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.MagicProjectile.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.MagicProjectile.Cost",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.ManaRecover",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.TeleportProjectile.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Player.TeleportProjectile.Cost",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Player.AnimCastProjectile",DevComment="")

